### ISSUE TITLE
WKDownloadHelper is compatible with iPhone but not working with iPad.

### ISSUE THREAD

**Issue by Thiru-09** [gualtierofrigerio/WKDownloadHelper#7]
I have checked the code base provided given as a reference in your docs, and I have found that WKDownloadHelper is not working with IPAD devices.
can you check me with the given issue.

**Comment by gualtierofrigerio** [comment]
I'm sorry I don't understand, maybe you are referring to one of the example where I use UIActivityViewController?
Because the rest of the code shouldn't deal with UI so I don't see why it shouldn't' work on the iPad

**Comment by Thiru-09** [comment]
what I'm trying to tell is, your code runs perfectly on iPhone but when I tried on iPad its not working I want to download the pdf files on iPad too ,if you have the code for iPad please let me know......

**Comment by gualtierofrigerio** [comment]
but I don't understand exactly what the problem is, you don't see the popover maybe?
If you download this project and you run it, does it work? https://github.com/gualtierofrigerio/WKWebViewDownloadHelper
You should see the popup from the navigation bar button item in this example

**Comment by Thiru-09** [comment]
yes , I didn't see the popover on iPad 

https://github.com/gualtierofrigerio/WKDownloadHelper/assets/119996617/68cfc9e6-3f98-4e82-97e5-41ef7d33b9fd

how to get the popover on iPad ?

**Comment by gualtierofrigerio** [comment]
I'll try to help you but posting a video is not going to make a difference here since there is no code, but anyway seems like you don't have a navigation bar with a button from where you can show it.
First, try this solution
https://stackoverflow.com/questions/62996746/ios-13-5-1-uiactivityviewcontroller-not-showing-on-ipad
and use the rect instead of the source view and see if it helps. 
Also this article could help https://dushyant37.medium.com/how-to-present-uiactivityviewcontroller-on-iphone-and-ipad-ae72013d2a5a

**Comment by Thiru-09** [comment]
thanks bro , now it works fine.....
that one line of code is missing 
<img width="859" alt="Screenshot 2023-09-13 at 1 14 12 PM" src="https://github.com/gualtierofrigerio/WKDownloadHelper/assets/119996617/396233ba-a9d9-4590-83d7-5ff6ac5fa344">

**Comment by gualtierofrigerio** [comment]
ok glad is fixed, if you find other issues on the library itself feel free to report :)

**Comment by Thiru-09** [comment]
yeah sure....
